### ISSUE TITLE
Out of Memory while trying to train with City scapes data set

### ISSUE THREAD

**Issue by saviogeorge** [alexgkendall/caffe-segnet#120]
Hi,

While trying to train the Segnet with the City scapes data set the GPU goes out of memory.
./SegNet/caffe-segnet/build/tools/caffe train -gpu 0 -solver /SegNet/Models/segnet_solver.prototxt
Please find the attached screenshot. 

The batch_size was reduced to 1 from 4 in the segnet_train.prototxt and also in the segnet_inference.prototxt. However the issue remains.

My Graphics card is GeForce GTX 1080 and i think this should not be a problem.
The city scapes data set resolution is :width=2048 and height 1024.
should I try by reducing the pixel sizes?

Please give your suggestions

![out of memory](https://user-images.githubusercontent.com/20711873/28268894-50fb30fc-6b00-11e7-974f-25a4d27f3a7b.png)
![graphics](https://user-images.githubusercontent.com/20711873/28268913-6573f0fa-6b00-11e7-8893-5ab6aca9e98c.png)

**Comment by saviogeorge** [comment]
I resized the image to 360x480 and went ahead. But i get the following error 
![annotations_problem](https://user-images.githubusercontent.com/20711873/28362780-0a7be2fa-6c7e-11e7-9151-36fdac7da364.png)

How can i change the annotations provided by city scapes to a form which is acceptable to segnet?

**Comment by saviogeorge** [comment]
This was solved by changing the batch_size = 1 to batch_size = 4
